// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_OVL_I10_A187510_H
#define OVERLAYS_OVL_I10_A187510_H

#include "gfx.h"

extern u16 aDDLoadingTex[];
#define _aDDLoadingTex_WIDTH 0x40
#define _aDDLoadingTex_HEIGHT 0x10
extern u16 aDDLoadBlueFalconTex[];
#define _aDDLoadBlueFalconTex_WIDTH 0x20
#define _aDDLoadBlueFalconTex_HEIGHT 0x10
extern u16 aDDLoadMachineTrailTex[];
#define _aDDLoadMachineTrailTex_WIDTH 0x20
#define _aDDLoadMachineTrailTex_HEIGHT 0x10

#endif
