#ifndef HUD_GFX_H
#define HUD_GFX_H

#include "gfx.h"

extern Gfx D_4000000[];
extern u16 aFirstPlaceMarker1PTex[];
#define _aFirstPlaceMarker1PTex_WIDTH 0x18
#define _aFirstPlaceMarker1PTex_HEIGHT 0x1e
extern u16 aSecondPlaceMarker1PTex[];
#define _aSecondPlaceMarker1PTex_WIDTH 0x18
#define _aSecondPlaceMarker1PTex_HEIGHT 0x1e
extern u16 aThirdPlaceMarker1PTex[];
#define _aThirdPlaceMarker1PTex_WIDTH 0x18
#define _aThirdPlaceMarker1PTex_HEIGHT 0x1e
extern u16 aFirstPlaceMarkerMPTex[];
#define _aFirstPlaceMarkerMPTex_WIDTH 0x10
#define _aFirstPlaceMarkerMPTex_HEIGHT 0x10
extern u16 aSecondPlaceMarkerMPTex[];
#define _aSecondPlaceMarkerMPTex_WIDTH 0x10
#define _aSecondPlaceMarkerMPTex_HEIGHT 0x10
extern u16 aThirdPlaceMarkerMPTex[];
#define _aThirdPlaceMarkerMPTex_WIDTH 0x10
#define _aThirdPlaceMarkerMPTex_HEIGHT 0x10
extern u16 aRivalMarkerTex[];
#define _aRivalMarkerTex_WIDTH 0x20
#define _aRivalMarkerTex_HEIGHT 0x10
extern u8 aCheckMarker1PTex[];
#define _aCheckMarker1PTex_WIDTH 0x20
#define _aCheckMarker1PTex_HEIGHT 0x17
extern u8 aCheckMarkerMPTex[];
#define _aCheckMarkerMPTex_WIDTH 0x10
#define _aCheckMarkerMPTex_HEIGHT 0xa
extern u16 aBoosterTrailTex[];
#define _aBoosterTrailTex_WIDTH 0x10
#define _aBoosterTrailTex_HEIGHT 0x10
extern u8 aExplosion1Tex[];
#define _aExplosion1Tex_WIDTH 0x20
#define _aExplosion1Tex_HEIGHT 0x20
extern u8 aExplosion2Tex[];
#define _aExplosion2Tex_WIDTH 0x20
#define _aExplosion2Tex_HEIGHT 0x20
extern u8 aExplosion3Tex[];
#define _aExplosion3Tex_WIDTH 0x20
#define _aExplosion3Tex_HEIGHT 0x20
extern u8 aExplosion4Tex[];
#define _aExplosion4Tex_WIDTH 0x20
#define _aExplosion4Tex_HEIGHT 0x20
extern u8 aExplosion5Tex[];
#define _aExplosion5Tex_WIDTH 0x20
#define _aExplosion5Tex_HEIGHT 0x20
extern u8 aExplosion6Tex[];
#define _aExplosion6Tex_WIDTH 0x20
#define _aExplosion6Tex_HEIGHT 0x20
extern u8 aExplosion7Tex[];
#define _aExplosion7Tex_WIDTH 0x20
#define _aExplosion7Tex_HEIGHT 0x20
extern u8 aExplosion8Tex[];
#define _aExplosion8Tex_WIDTH 0x20
#define _aExplosion8Tex_HEIGHT 0x20
extern u8 aSupernovaTex[];
#define _aSupernovaTex_WIDTH 0x20
#define _aSupernovaTex_HEIGHT 0x100
extern u8 aSmokeEffectTex[];
#define _aSmokeEffectTex_WIDTH 0x20
#define _aSmokeEffectTex_HEIGHT 0x100
extern u8 aPitForceFieldTex[];
#define _aPitForceFieldTex_WIDTH 0x20
#define _aPitForceFieldTex_HEIGHT 0x100
extern u8 aFallExplosionTex[];
#define _aFallExplosionTex_WIDTH 0x40
#define _aFallExplosionTex_HEIGHT 0x80
extern Gfx D_4007EA8[];
extern Gfx aSetupBoosterDL[];
extern Gfx D_4007FB8[];
extern Gfx D_4007FD8[];
extern Gfx D_4008000[];
extern Gfx D_4008028[];
extern Gfx D_4008130[];
extern Gfx aSetupPitForceFieldDL[];
extern Gfx aSetupFallExplosionDL[];
extern Gfx D_4008250[];
extern u16 aCountdown3Tex[];
#define _aCountdown3Tex_WIDTH 0x20
#define _aCountdown3Tex_HEIGHT 0x20
extern u16 aCountdown2Tex[];
#define _aCountdown2Tex_WIDTH 0x20
#define _aCountdown2Tex_HEIGHT 0x20
extern u16 aCountdown1Tex[];
#define _aCountdown1Tex_WIDTH 0x20
#define _aCountdown1Tex_HEIGHT 0x20
extern u16 aCountdownGoTex[];
#define _aCountdownGoTex_WIDTH 0x20
#define _aCountdownGoTex_HEIGHT 0x20
extern Gfx D_400A258[];
extern Gfx aCountdownSignDL[];
extern Gfx D_400A480[];
extern Vtx D_400A4A8[];
extern Vtx D_400A568[];
extern Vtx D_400A5E8[];
extern Vtx D_400A628[];
extern Vtx D_400A668[];
extern Vtx D_400A728[];
extern Vtx D_400A7A8[];
extern Vtx D_400A7E8[];
extern Vtx D_400A828[];
extern Vtx D_400A868[];
extern Vtx aCountdownSignGrates3Vtx[];
extern Vtx D_400AA28[];
extern u16 aCountdownSignGratesTex[];
#define _aCountdownSignGratesTex_WIDTH 0x20
#define _aCountdownSignGratesTex_HEIGHT 0x20
extern u16 aCountdownMrZeroMouthClosedTex[];
#define _aCountdownMrZeroMouthClosedTex_WIDTH 0x20
#define _aCountdownMrZeroMouthClosedTex_HEIGHT 0x20
extern u16 aCountdownMrZeroMouthOpenTex[];
#define _aCountdownMrZeroMouthOpenTex_WIDTH 0x20
#define _aCountdownMrZeroMouthOpenTex_HEIGHT 0x20
extern Gfx aGameoverDL[];
extern Gfx D_400C9B0[];
extern Gfx aExecuteGameoverDL[];
extern Gfx D_400C9D0[];
extern Vtx D_400C9D8[];
extern Vtx D_400CBD8[];
extern Vtx D_400CDD8[];
extern Vtx D_400CFD8[];
extern Vtx D_400D1D8[];
extern Vtx D_400D3D8[];
extern Vtx D_400D5D8[];
extern Vtx D_400D7D8[];
extern Vtx D_400D958[];
extern Vtx D_400DB58[];
extern Vtx D_400DD58[];
extern Vtx D_400DF58[];
extern Vtx D_400E158[];
extern Vtx D_400E358[];
extern Vtx D_400E558[];
extern Vtx D_400E758[];
extern Vtx D_400E958[];
extern u16 aGameoverFaceTex[];
#define _aGameoverFaceTex_WIDTH 0x10
#define _aGameoverFaceTex_HEIGHT 0x10
extern u16 aGameoverSideTex[];
#define _aGameoverSideTex_WIDTH 0x8
#define _aGameoverSideTex_HEIGHT 0x8
extern u8 aFinalLapTex[];
#define _aFinalLapTex_WIDTH 0x80
#define _aFinalLapTex_HEIGHT 0x10
extern u16 aFinalLapPalette[];
#define _aFinalLapPalette_WIDTH 0x10
#define _aFinalLapPalette_HEIGHT 0x1
extern u8 aBoosterOkTex[];
#define _aBoosterOkTex_WIDTH 0x50
#define _aBoosterOkTex_HEIGHT 0x10
extern u16 aBoosterOkPalette[];
#define _aBoosterOkPalette_WIDTH 0x100
#define _aBoosterOkPalette_HEIGHT 0x1
extern Gfx aFinishDL[];
extern Gfx D_40104F0[];
extern Vtx D_40104F8[];
extern Vtx D_4010598[];
extern Vtx D_40105D8[];
extern Vtx D_4010678[];
extern Vtx D_40106B8[];
extern Vtx D_4010818[];
extern Vtx D_40108D8[];
extern Vtx D_4010A58[];
extern Vtx D_4010B18[];
extern Vtx D_4010D18[];
extern Vtx D_4010E58[];
extern Vtx D_4010FB8[];
extern Vtx D_4011038[];
extern Vtx D_4011078[];
extern Vtx D_40111B8[];
extern Vtx D_4011258[];
extern Vtx D_40112D8[];
extern Vtx D_4011318[];
extern Vtx D_4011458[];
extern u16 aFinishFaceTex[];
#define _aFinishFaceTex_WIDTH 0x10
#define _aFinishFaceTex_HEIGHT 0x10
extern u16 aFinishSideTex[];
#define _aFinishSideTex_WIDTH 0x8
#define _aFinishSideTex_HEIGHT 0x8
extern u16 aStartStopGuideTex[];
#define _aStartStopGuideTex_WIDTH 0x40
#define _aStartStopGuideTex_HEIGHT 0xc
extern Gfx aMenuTextTlutSetupDL[];
extern u8 aReverseTex[];
#define _aReverseTex_WIDTH 0x70
#define _aReverseTex_HEIGHT 0x2e
extern u16 aReversePalette[];
#define _aReversePalette_WIDTH 0x10
#define _aReversePalette_HEIGHT 0x1
extern u16 aHudTimeTex[];
#define _aHudTimeTex_WIDTH 0x18
#define _aHudTimeTex_HEIGHT 0x10
extern u16 aHudEnergyTex[];
#define _aHudEnergyTex_WIDTH 0x48
#define _aHudEnergyTex_HEIGHT 0x10
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aPositionDigitTexs[][896];
extern u16 aRacersLeftTex[];
#define _aRacersLeftTex_WIDTH 0x20
#define _aRacersLeftTex_HEIGHT 0x10
extern u16 aTotalRacerDigitsTex[];
#define _aTotalRacerDigitsTex_WIDTH 0x8
#define _aTotalRacerDigitsTex_HEIGHT 0x84
extern u16 aPositionOrdinalSuffixTexs[][400];
extern u16 aPositionOrdinalSuffixTexs[][400];
extern u16 aPositionOrdinalSuffixTexs[][400];
extern u16 aPositionOrdinalSuffixTexs[][400];
extern u16 aLapCounterSymbolsTex[];
#define _aLapCounterSymbolsTex_WIDTH 0x8
#define _aLapCounterSymbolsTex_HEIGHT 0x48
extern u16 aCharacterPortraitHighlightBorderTex[];
#define _aCharacterPortraitHighlightBorderTex_WIDTH 0x20
#define _aCharacterPortraitHighlightBorderTex_HEIGHT 0x20
extern u16 aHudLivesLeftIconTex[];
#define _aHudLivesLeftIconTex_WIDTH 0x8
#define _aHudLivesLeftIconTex_HEIGHT 0x8
extern u16 aHudRacersKOdTex[];
#define _aHudRacersKOdTex_WIDTH 0x8
#define _aHudRacersKOdTex_HEIGHT 0x8
extern u16 aPortraitCaptainFalconTex[];
#define _aPortraitCaptainFalconTex_WIDTH 0x20
#define _aPortraitCaptainFalconTex_HEIGHT 0x20
extern u16 aPortraitSamuraiGorohTex[];
#define _aPortraitSamuraiGorohTex_WIDTH 0x20
#define _aPortraitSamuraiGorohTex_HEIGHT 0x20
extern u16 aPortraitJodySummerTex[];
#define _aPortraitJodySummerTex_WIDTH 0x20
#define _aPortraitJodySummerTex_HEIGHT 0x20
extern u16 aPortraitAntonioGusterTex[];
#define _aPortraitAntonioGusterTex_WIDTH 0x20
#define _aPortraitAntonioGusterTex_HEIGHT 0x20
extern u16 aPortraitSuperArrowTex[];
#define _aPortraitSuperArrowTex_WIDTH 0x20
#define _aPortraitSuperArrowTex_HEIGHT 0x20
extern u16 aPortraitBloodFalconTex[];
#define _aPortraitBloodFalconTex_WIDTH 0x20
#define _aPortraitBloodFalconTex_HEIGHT 0x20
extern u16 aPortraitBeastmanTex[];
#define _aPortraitBeastmanTex_WIDTH 0x20
#define _aPortraitBeastmanTex_HEIGHT 0x20
extern u16 aPortraitBillyTex[];
#define _aPortraitBillyTex_WIDTH 0x20
#define _aPortraitBillyTex_HEIGHT 0x20
extern u16 aPortraitBlackShadowTex[];
#define _aPortraitBlackShadowTex_WIDTH 0x20
#define _aPortraitBlackShadowTex_HEIGHT 0x20
extern u16 aPortraitRogerBusterTex[];
#define _aPortraitRogerBusterTex_WIDTH 0x20
#define _aPortraitRogerBusterTex_HEIGHT 0x20
extern u16 aPortraitDraqTex[];
#define _aPortraitDraqTex_WIDTH 0x20
#define _aPortraitDraqTex_HEIGHT 0x20
extern u16 aPortraitDrClashTex[];
#define _aPortraitDrClashTex_WIDTH 0x20
#define _aPortraitDrClashTex_HEIGHT 0x20
extern u16 aPortraitMrEadTex[];
#define _aPortraitMrEadTex_WIDTH 0x20
#define _aPortraitMrEadTex_HEIGHT 0x20
extern u16 aPortraitGomarAndShiohTex[];
#define _aPortraitGomarAndShiohTex_WIDTH 0x20
#define _aPortraitGomarAndShiohTex_HEIGHT 0x20
extern u16 aPortraitJackLevinTex[];
#define _aPortraitJackLevinTex_WIDTH 0x20
#define _aPortraitJackLevinTex_HEIGHT 0x20
extern u16 aPortraitJamesMcCloudTex[];
#define _aPortraitJamesMcCloudTex_WIDTH 0x20
#define _aPortraitJamesMcCloudTex_HEIGHT 0x20
extern u16 aPortraitSilverNeelsenTex[];
#define _aPortraitSilverNeelsenTex_WIDTH 0x20
#define _aPortraitSilverNeelsenTex_HEIGHT 0x20
extern u16 aPortraitKateAlenTex[];
#define _aPortraitKateAlenTex_WIDTH 0x20
#define _aPortraitKateAlenTex_HEIGHT 0x20
extern u16 aPortraitMichaelChainTex[];
#define _aPortraitMichaelChainTex_WIDTH 0x20
#define _aPortraitMichaelChainTex_HEIGHT 0x20
extern u16 aPortraitOctomanTex[];
#define _aPortraitOctomanTex_WIDTH 0x20
#define _aPortraitOctomanTex_HEIGHT 0x20
extern u16 aPortraitPicoTex[];
#define _aPortraitPicoTex_WIDTH 0x20
#define _aPortraitPicoTex_HEIGHT 0x20
extern u16 aPortraitLeonTex[];
#define _aPortraitLeonTex_WIDTH 0x20
#define _aPortraitLeonTex_HEIGHT 0x20
extern u16 aPortraitBioRexTex[];
#define _aPortraitBioRexTex_WIDTH 0x20
#define _aPortraitBioRexTex_HEIGHT 0x20
extern u16 aPortraitMightyGazelleTex[];
#define _aPortraitMightyGazelleTex_WIDTH 0x20
#define _aPortraitMightyGazelleTex_HEIGHT 0x20
extern u16 aPortraitDrStewartTex[];
#define _aPortraitDrStewartTex_WIDTH 0x20
#define _aPortraitDrStewartTex_HEIGHT 0x20
extern u16 aPortraitJohnTanakaTex[];
#define _aPortraitJohnTanakaTex_WIDTH 0x20
#define _aPortraitJohnTanakaTex_HEIGHT 0x20
extern u16 aPortraitBabaTex[];
#define _aPortraitBabaTex_WIDTH 0x20
#define _aPortraitBabaTex_HEIGHT 0x20
extern u16 aPortraitMrsArrowTex[];
#define _aPortraitMrsArrowTex_WIDTH 0x20
#define _aPortraitMrsArrowTex_HEIGHT 0x20
extern u16 aPortraitZodaTex[];
#define _aPortraitZodaTex_WIDTH 0x20
#define _aPortraitZodaTex_HEIGHT 0x20
extern u16 aPortraitTheSkullTex[];
#define _aPortraitTheSkullTex_WIDTH 0x20
#define _aPortraitTheSkullTex_HEIGHT 0x20
extern u16 aPortraitPositionFirstTex[];
#define _aPortraitPositionFirstTex_WIDTH 0x10
#define _aPortraitPositionFirstTex_HEIGHT 0x6
extern u16 aPortraitPositionSecondTex[];
#define _aPortraitPositionSecondTex_WIDTH 0x10
#define _aPortraitPositionSecondTex_HEIGHT 0x6
extern u16 aPortraitPositionThirdTex[];
#define _aPortraitPositionThirdTex_WIDTH 0x10
#define _aPortraitPositionThirdTex_HEIGHT 0x6
extern u16 aPortraitPositionFourthTex[];
#define _aPortraitPositionFourthTex_WIDTH 0x10
#define _aPortraitPositionFourthTex_HEIGHT 0x6
extern u16 aPortraitPositionFifthTex[];
#define _aPortraitPositionFifthTex_WIDTH 0x10
#define _aPortraitPositionFifthTex_HEIGHT 0x6
extern u16 aPortraitPositionSixthTex[];
#define _aPortraitPositionSixthTex_WIDTH 0x10
#define _aPortraitPositionSixthTex_HEIGHT 0x6

#endif
