// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_COURSE_SELECT_COURSE_SELECT_H
#define OVERLAYS_COURSE_SELECT_COURSE_SELECT_H

#include "gfx.h"

extern u16 aCupSelectDD1Tex[];
#define _aCupSelectDD1Tex_WIDTH 0x40
#define _aCupSelectDD1Tex_HEIGHT 0x40
#define _aCupSelectDD1Tex_COMPRESSED_SIZE 0x498
extern u16 aCupSelectDD2Tex[];
#define _aCupSelectDD2Tex_WIDTH 0x40
#define _aCupSelectDD2Tex_HEIGHT 0x40
#define _aCupSelectDD2Tex_COMPRESSED_SIZE 0xd54

#endif
