// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_OVL_I4_MACHINE_H
#define OVERLAYS_OVL_I4_MACHINE_H

#include "gfx.h"

extern u16 aNoviceDDTrophyTex[];
#define _aNoviceDDTrophyTex_WIDTH 0x10
#define _aNoviceDDTrophyTex_HEIGHT 0x10
#define _aNoviceDDTrophyTex_COMPRESSED_SIZE 0x90
extern u16 aStandardDDTrophyTex[];
#define _aStandardDDTrophyTex_WIDTH 0x10
#define _aStandardDDTrophyTex_HEIGHT 0x10
#define _aStandardDDTrophyTex_COMPRESSED_SIZE 0xa4
extern u16 aExpertDDTrophyTex[];
#define _aExpertDDTrophyTex_WIDTH 0x10
#define _aExpertDDTrophyTex_HEIGHT 0x10
#define _aExpertDDTrophyTex_COMPRESSED_SIZE 0xa4
extern u16 aMasterDDTrophyTex[];
#define _aMasterDDTrophyTex_WIDTH 0x10
#define _aMasterDDTrophyTex_HEIGHT 0x10
#define _aMasterDDTrophyTex_COMPRESSED_SIZE 0x1f24

#endif
