// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_OVL_I4_TITLE_H
#define OVERLAYS_OVL_I4_TITLE_H

#include "gfx.h"

extern u16 aN64DDLogoTex[];
#define _aN64DDLogoTex_WIDTH 0x38
#define _aN64DDLogoTex_HEIGHT 0x11
#define _aN64DDLogoTex_COMPRESSED_SIZE 0x2c4
extern u16 aCopyrightDDTex[];
#define _aCopyrightDDTex_WIDTH 0xc0
#define _aCopyrightDDTex_HEIGHT 0xe
#define _aCopyrightDDTex_COMPRESSED_SIZE 0x6f8

#endif
