// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef AUDIO_SEQ_DD_H
#define AUDIO_SEQ_DD_H

#include "gfx.h"

extern u8 aAudioSeqDDGuitar[];
extern u8 aAudioSeqDDSE[];
extern u8 aAudioSeqDDMuteCity[];
extern u8 aAudioSeqDDSilence[];
extern u8 aAudioSeqDDSandOcean[];
extern u8 aAudioSeqDDPortTown[];
extern u8 aAudioSeqDDBigBlue[];
extern u8 aAudioSeqDDDevilsForest[];
extern u8 aAudioSeqDDRedCanyon[];
extern u8 aAudioSeqDDSector[];
extern u8 aAudioSeqDDWhiteLand[];
extern u8 aAudioSeqDDRainbowRoad[];
extern u8 aAudioSeqDDNew03[];
extern u8 aAudioSeqDDNew02[];
extern u8 aAudioSeqDDNew01[];
extern u8 aAudioSeqDDNew04[];
extern u8 aAudioSeqDDTitle[];
extern u8 aAudioSeqDDSelect[];
extern u8 aAudioSeqDDOption[];
extern u8 aAudioSeqDDDeathRace[];
extern u8 aAudioSeqDDCourseEditor[];
extern u8 aAudioSeqDDMachineEditor[];
extern u8 aAudioSeqDDEADDemo[];

#endif
