// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef AUDIO_BANK_DD_H
#define AUDIO_BANK_DD_H

#include "gfx.h"

extern u8 aAudioSoundFontDDGuitar[];
extern u8 aAudioSoundFontDDSE[];
extern u8 aAudioSoundFontDDMuteCity[];
extern u8 aAudioSoundFontDDSilence[];
extern u8 aAudioSoundFontDDSandOcean[];
extern u8 aAudioSoundFontDDPortTown[];
extern u8 aAudioSoundFontDDBigBlue[];
extern u8 aAudioSoundFontDDDevilsForest[];
extern u8 aAudioSoundFontDDRedCanyon[];
extern u8 aAudioSoundFontDDSector[];
extern u8 aAudioSoundFontDDWhiteLand[];
extern u8 aAudioSoundFontDDRainbowRoad[];
extern u8 aAudioSoundFontDDNew03[];
extern u8 aAudioSoundFontDDNew02[];
extern u8 aAudioSoundFontDDNew01[];
extern u8 aAudioSoundFontDDNew04[];
extern u8 aAudioSoundFontDDTitle[];
extern u8 aAudioSoundFontDDSelect[];
extern u8 aAudioSoundFontDDOption[];
extern u8 aAudioSoundFontDDDeathRace[];
extern u8 aAudioSoundFontDDCourseEditor[];
extern u8 aAudioSoundFontDDMachineEditor[];
extern u8 aAudioSoundFontDDEADDemo[];

#endif
