// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef BOOT_LOGO_H
#define BOOT_LOGO_H

#include "gfx.h"

extern u16 D_80769DF0[];
#define _D_80769DF0_WIDTH 0x88
#define _D_80769DF0_HEIGHT 0x27

#endif
