// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_RECORDS_RECORDS_ASSETS_H
#define OVERLAYS_RECORDS_RECORDS_ASSETS_H

#include "gfx.h"

extern Gfx D_i8_8009E2B8[];
extern u8 aRecordsWhichGhostToCopyTex[];
#define _aRecordsWhichGhostToCopyTex_WIDTH 0x80
#define _aRecordsWhichGhostToCopyTex_HEIGHT 0x10
extern Gfx D_i8_8009EAC0[];
extern u16 aRecordsWhichGhostToCopyPalette[];
#define _aRecordsWhichGhostToCopyPalette_WIDTH 0x0
#define _aRecordsWhichGhostToCopyPalette_HEIGHT 0x0
extern Gfx D_i8_8009EB08[];
extern u8 aRecordsWhereToCopyTex[];
#define _aRecordsWhereToCopyTex_WIDTH 0x80
#define _aRecordsWhereToCopyTex_HEIGHT 0x10
extern Gfx D_i8_8009F310[];
extern u16 aRecordsWhereToCopyPalette[];
#define _aRecordsWhereToCopyPalette_WIDTH 0x0
#define _aRecordsWhereToCopyPalette_HEIGHT 0x0
extern Gfx D_i8_8009F358[];
extern u8 aMenuCopyGhostTex[];
#define _aMenuCopyGhostTex_WIDTH 0x40
#define _aMenuCopyGhostTex_HEIGHT 0x10
extern Gfx D_i8_8009F760[];
extern u16 aMenuCopyGhostPalette[];
#define _aMenuCopyGhostPalette_WIDTH 0x0
#define _aMenuCopyGhostPalette_HEIGHT 0x0
extern Gfx D_i8_8009F7A8[];
extern u8 aRecordsGhostCopiedTex[];
#define _aRecordsGhostCopiedTex_WIDTH 0x40
#define _aRecordsGhostCopiedTex_HEIGHT 0x10
extern Gfx D_i8_8009FBB0[];
extern u16 aRecordsGhostCopiedPalette[];
#define _aRecordsGhostCopiedPalette_WIDTH 0x0
#define _aRecordsGhostCopiedPalette_HEIGHT 0x0
extern Gfx D_i8_8009FBF8[];
extern u8 aRecordsCassetteGhostTex[];
#define _aRecordsCassetteGhostTex_WIDTH 0x40
#define _aRecordsCassetteGhostTex_HEIGHT 0x10
extern Gfx D_i8_800A0000[];
extern u16 aRecordsCassetteGhostPalette[];
#define _aRecordsCassetteGhostPalette_WIDTH 0x0
#define _aRecordsCassetteGhostPalette_HEIGHT 0x0
extern Gfx D_i8_800A0048[];
extern u8 aRecordsDiskGhost1Tex[];
#define _aRecordsDiskGhost1Tex_WIDTH 0x40
#define _aRecordsDiskGhost1Tex_HEIGHT 0x10
extern Gfx D_i8_800A0450[];
extern u16 aRecordsDiskGhost1Palette[];
#define _aRecordsDiskGhost1Palette_WIDTH 0x0
#define _aRecordsDiskGhost1Palette_HEIGHT 0x0
extern Gfx D_i8_800A0498[];
extern u8 aRecordsDiskGhost2Tex[];
#define _aRecordsDiskGhost2Tex_WIDTH 0x40
#define _aRecordsDiskGhost2Tex_HEIGHT 0x10
extern Gfx D_i8_800A08A0[];
extern u16 aRecordsDiskGhost2Palette[];
#define _aRecordsDiskGhost2Palette_WIDTH 0x0
#define _aRecordsDiskGhost2Palette_HEIGHT 0x0
extern Gfx D_i8_800A08E8[];
extern u8 aRecordsDiskGhost3Tex[];
#define _aRecordsDiskGhost3Tex_WIDTH 0x40
#define _aRecordsDiskGhost3Tex_HEIGHT 0x10
extern Gfx D_i8_800A0CF0[];
extern u16 aRecordsDiskGhost3Palette[];
#define _aRecordsDiskGhost3Palette_WIDTH 0x0
#define _aRecordsDiskGhost3Palette_HEIGHT 0x0
extern Gfx D_i8_800A0D38[];
extern u8 aRecordsInsertDiskToCopyToTex[];
#define _aRecordsInsertDiskToCopyToTex_WIDTH 0x80
#define _aRecordsInsertDiskToCopyToTex_HEIGHT 0x20
extern Gfx D_i8_800A1D40[];
extern u16 aRecordsInsertDiskToCopyToPalette[];
#define _aRecordsInsertDiskToCopyToPalette_WIDTH 0x0
#define _aRecordsInsertDiskToCopyToPalette_HEIGHT 0x0

#endif
