// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_BIG_FOOT_STAFF_GHOST_H
#define GHOSTS_BIG_FOOT_STAFF_GHOST_H

#include "gfx.h"

extern u8 aBigFootStaffGhost[];

#endif
