// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_DEVILS_FOREST_5_STAFF_GHOST_H
#define GHOSTS_DEVILS_FOREST_5_STAFF_GHOST_H

#include "gfx.h"

extern u8 aDevilsForest5StaffGhost[];

#endif
