// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_FIRE_FIELD_2_STAFF_GHOST_H
#define GHOSTS_FIRE_FIELD_2_STAFF_GHOST_H

#include "gfx.h"

extern u8 aFireField2StaffGhost[];

#endif
