// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_MUTE_CITY_4_STAFF_GHOST_H
#define GHOSTS_MUTE_CITY_4_STAFF_GHOST_H

#include "gfx.h"

extern u8 aMuteCity4StaffGhost[];

#endif
