// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_PORT_TOWN_3_STAFF_GHOST_H
#define GHOSTS_PORT_TOWN_3_STAFF_GHOST_H

#include "gfx.h"

extern u8 aPortTown3StaffGhost[];

#endif
