// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_SPACE_PLANT_2_STAFF_GHOST_H
#define GHOSTS_SPACE_PLANT_2_STAFF_GHOST_H

#include "gfx.h"

extern u8 aSpacePlant2StaffGhost[];

#endif
