// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef GHOSTS_WHITE_LAND_3_STAFF_GHOST_H
#define GHOSTS_WHITE_LAND_3_STAFF_GHOST_H

#include "gfx.h"

extern u8 aWhiteLand3StaffGhost[];

#endif
