// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_EXPANSION_KIT_AA3AE0_H
#define OVERLAYS_EXPANSION_KIT_AA3AE0_H

#include "gfx.h"

extern u8 D_xk1_800302F0[];
#define _D_xk1_800302F0_WIDTH 0x30
#define _D_xk1_800302F0_HEIGHT 0x10
extern u8 D_xk1_80030470[];
#define _D_xk1_80030470_WIDTH 0x30
#define _D_xk1_80030470_HEIGHT 0x10

#endif
