// AUTO-GENERATED by tools/gen_ek_assets.py. Do not edit by hand.
#ifndef OVERLAYS_EXPANSION_KIT_DD_FAULT_H
#define OVERLAYS_EXPANSION_KIT_DD_FAULT_H

#include "gfx.h"

extern Gfx D_xk1_800335F0[];
extern Gfx D_xk1_80033630[];

#endif
