#!/usr/bin/env python3
"""Generate family_manifest.json from a reference .o2r archive.

The manifest is the source of truth for validate_archive.py's
"complete-or-absent" family check (C6): every category family must appear with
its full expected entry count, or not at all. Because Path B (the SETTIMG OTR
rewrite) is not resilient to a *partial* archive, a family that is present but
short is a silent texture-corruption bug -- the manifest lets validation catch
it without booting the game.

The manifest is generated from the deterministic archive
(assets/extracted/generic.o2r) and committed. It encodes the C3 full-recipe
output (currently 3,601 records including the inert families, the R1
segment_blob family, and the R2 audio_blob family), so it also serves as the
frozen per-family breakdown of the golden. Entry counts are central-directory
RECORDS (dup-inclusive), matching the runtime gate.

Usage:
  gen_family_manifest.py --archive PATH --out family_manifest.json
"""

import argparse
import json
import os
import sys

import o2r_common as oc

# Families the consumer contract (W0 section 1) marks as inert: present in the
# full recipe output but read by no O2R consumer. Recorded so validation can
# report them distinctly; they are still count-checked like every other family.
INERT_FAMILIES = [
    "course_data",
    "staff_ghost_records",
    "super_textures",
    "boot_textures",
    "audio_bank",
    "audio_seq",
    "version",
    "portVersion",
]


def build_manifest(archive):
    counts = oc.family_counts(archive)
    total = sum(counts.values())
    families = {}
    for fam in sorted(counts):
        families[fam] = {
            "count": counts[fam],
            "inert": fam in INERT_FAMILIES,
        }
    return {
        "_comment": (
            "Generated by tools/o2r_harness/gen_family_manifest.py from a "
            "reference generic.o2r. Source of truth for the complete-or-absent "
            "family check (P0 contract C6). Regenerate only when the recipe set "
            "intentionally changes."
        ),
        "source_archive": os.path.basename(archive),
        "source_sha256": oc.sha256_file(archive),
        "total_entries": total,
        "expected_entry_count": oc.EXPECTED_ENTRY_COUNT,
        "families": families,
    }


def main(argv):
    ap = argparse.ArgumentParser(description="Generate family_manifest.json.")
    ap.add_argument(
        "--archive",
        default=os.path.join(
            os.path.dirname(__file__),
            "..",
            "..",
            "assets",
            "extracted",
            "generic.o2r",
        ),
        help="reference .o2r to derive family counts from (default: legacy archive)",
    )
    ap.add_argument(
        "--out",
        default=os.path.join(os.path.dirname(__file__), "family_manifest.json"),
        help="output manifest path",
    )
    args = ap.parse_args(argv)

    if not os.path.isfile(args.archive):
        print("ERROR: archive not found: %s" % args.archive, file=sys.stderr)
        return 2

    manifest = build_manifest(args.archive)
    # Deterministic JSON: sorted keys, trailing newline.
    with open(args.out, "w", encoding="utf-8", newline="\n") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")

    print("Wrote %s" % args.out)
    print("  source        : %s" % manifest["source_archive"])
    print("  source sha256 : %s" % manifest["source_sha256"])
    print("  total entries : %d" % manifest["total_entries"])
    print("  families      : %d" % len(manifest["families"]))
    if manifest["total_entries"] != oc.EXPECTED_ENTRY_COUNT:
        print(
            "  WARNING: total %d != C3 expected %d"
            % (manifest["total_entries"], oc.EXPECTED_ENTRY_COUNT)
        )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
